name: play_command
description: A CLI to play games
version: 1.0.0
repository: https://github.com/georges-ph/play_command

environment:
  sdk: ^3.0.5

dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
